language: php
php:
  - 5.6
  - 5.5
  - 5.4
  
   
before_script:
  - composer install 
  - mysql -e 'CREATE DATABASE general_ledger;'
  - mysql general_ledger < database/database.sql
  
script: vendor/bin/phpunit --configuration travis.xml